# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-03 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id_recurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('archivo_recurso', models.FileField(upload_to='recursos/')),
            ],
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TagRecurso',
            fields=[
                ('id_tag', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('id_tipo_recurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('extension', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=70)),
                ('apellidos', models.CharField(max_length=70)),
                ('correo', models.EmailField(max_length=70)),
                ('telefono', models.CharField(max_length=70)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=70)),
                ('fecha_creacion', models.DateField()),
                ('fecha_modificacion', models.DateField()),
                ('rol_usuario', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='portal.RolUsuario')),
            ],
        ),
        migrations.AddField(
            model_name='recurso',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='portal.Usuario'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='tag_recurso',
            field=models.ForeignKey(db_column='id_tag', on_delete=django.db.models.deletion.CASCADE, to='portal.TagRecurso'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='tipo_recurso',
            field=models.ForeignKey(db_column='id_tipo_recurso', on_delete=django.db.models.deletion.CASCADE, to='portal.TipoRecurso'),
        ),
    ]
