# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-07 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('fecha_modificacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('fecha_modificacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id_recurso', models.AutoField(default='', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('tipo_recurso', models.CharField(choices=[('Imagen', 'Imagen'), ('Video', 'Video'), ('3D', '3D'), ('PDF', 'PDF'), ('MP3', 'MP3')], default='', max_length=50)),
                ('id_asignatura', models.ForeignKey(db_column='id_asignatura', default='', on_delete=django.db.models.deletion.CASCADE, to='portal.Asignatura')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='id_carrera',
            field=models.ForeignKey(db_column='id_carrera', default='', on_delete=django.db.models.deletion.CASCADE, to='portal.Carrera'),
        ),
    ]
