# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-05 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='recursos/'),
        ),
    ]
