# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-07 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_recurso_archivo_recurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='archivo_recurso',
            field=models.FileField(upload_to='static/'),
        ),
    ]
