# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-06 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_asignatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('fecha_modificacion', models.DateField()),
                ('carrera_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Asignatura')),
            ],
        ),
    ]
