# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-06 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_carrera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='carrera_asignatura',
        ),
    ]
